// Auth
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';

// Home
export const GET_ALL_HOME_INFO = 'GET_ALL_HOME_INFO';
export const GET_RECORD = 'GET_RECORD';

/**
 * 产品相关
 */

/**
 * @module Fixed 定期产品相关
 */
export const GET_ALL_FIXED_PRODUCT = 'GET_ALL_FIXED_PRODUCT';
export const GET_FIXED_PRODUCT_BY_ID = 'GET_FIXED_PRODUCT_BY_ID';
export const GET_FIXED_BUY_INFO = 'GET_FIXED_BUY_INFO';
export const GET_AVAILABEL_COUPONS = 'GET_AVAILABEL_COUPONS';

/**
 * @module Current 活期产品相关
 */
export const GET_ALL_CURRENT_PRODUCT = 'GET_ALL_CURRENT_PRODUCT';
export const GET_CURRENT_CURRENCIES = 'GET_CURRENT_CURRENCIES';
export const GET_CURRENT_TRADE_RECORDS = 'GET_CURRENT_TRADE_RECORDS';
export const GET_HISTORY_INTEREST_RATE = 'GET_HISTORY_INTEREST_RATE';
export const GET_HISTORY_PROFIT = 'GET_HISTORY_PROFIT';
export const GET_CURRENT_BUY_INFO = 'GET_CURRENT_BUY_INFO';
export const GET_CURRENT_SELL_INFO = 'GET_CURRENT_SELL_INFO';
export const GET_CURRENT_BUY_RESULT = 'GET_CURRENT_BUY_RESULT';
export const GET_CURRENT_SELL_RESULT = 'GET_CURRENT_SELL_RESULT';

/**
 * @module Fund 基金产品相关
 */
export const GET_FUND_PRODUCTS = 'GET_FUND_PRODUCTS';
export const GET_FUND_CURRENCIES = 'GET_FUND_CURRENCIES';
export const GET_FUND_PRODUCT_DETAIL = 'GET_FUND_PRODUCT_DETAIL';
export const GET_FUND_BUY_INFO = 'GET_FUND_BUY_INFO';
export const GET_HOLDING_FUNDS = 'GET_HOLDING_FUNDS';
export const BUY_FUNDS = 'BUY_FUNDS';
export const GET_FUNDS_TRADE_RULES = 'GET_FUNDS_TRADE_RULES';
export const GET_FUNDS_INFORMATION = 'GET_FUNDS_INFORMATION';
export const GET_FUNDS_ORDER_HISTORY = 'GET_FUNDS_ORDER_HISTORY';
export const GET_FUNDS_ORDER_DETAIL = 'GET_FUNDS_ORDER_DETAIL';
export const GET_FUND_OWNER_DETAIL = 'GET_FUND_OWNER_DETAIL';

/**
 * 用户相关
 */
export const GET_USER_SUMMARY = 'GET_USER_SUMMARY';
export const GET_KYC_INFO = 'GET_KYC_INFO';
export const GET_USER_BALANCE_SUMMARY = 'GET_USER_BALANCE_SUMMARY';
export const GET_SUBMIT_KYC_RESULT = 'GET_SUBMIT_KYC_RESULT';

/**
 * 冲币买币
 */
export const GET_PURCHASE_INFO = 'GET_PURCHASE_INFO';
export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_CURRENCY_PRICE = 'GET_CURRENCY_PRICE';
export const GET_ORDER_INFO = 'GET_ORDER_INFO';
export const POST_USER_APPEAL = 'POST_USER_APPEAL'; // 用户提交申诉
export const GET_ORDER_INFO_BY_ID = 'GET_ORDER_INFO_BY_ID'; // 根据ID查询订单 GET_ORDER_LIST
export const GET_ORDER_LIST = 'GET_ORDER_LIST'; // 订单列表
export const CHECK_PAY_TYPE_INFO = 'CHECK_PAY_TYPE_INFO'; // 选择支付方式 生成的信息

/**
 * App 相关
 */
export const GET_UPLOAD_POLICY = 'GET_UPLOAD_POLICY';
