// Auth
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';

// Home
export const GET_ALL_HOME_INFO = 'GET_ALL_HOME_INFO';

/**
 * 产品相关
 */

/**
 * @module Fixed 定期产品相关
 */
export const GET_ALL_FIXED_PRODUCT = 'GET_ALL_FIXED_PRODUCT';
export const GET_FIXED_PRODUCT_BY_ID = 'GET_FIXED_PRODUCT_BY_ID';
export const GET_FIXED_BUY_INFO = 'GET_FIXED_BUY_INFO';
export const GET_AVAILABEL_COUPONS = 'GET_AVAILABEL_COUPONS';

/**
 * @module Current 活期产品相关
 */
export const GET_ALL_CURRENT_PRODUCT = 'GET_ALL_CURRENT_PRODUCT';
export const GET_CURRENT_CURRENCIES = 'GET_CURRENT_CURRENCIES';
export const GET_CURRENT_TRADE_RECORDS = 'GET_CURRENT_TRADE_RECORDS';
export const GET_HISTORY_INTEREST_RATE = 'GET_HISTORY_INTEREST_RATE';
export const GET_HISTORY_PROFIT = 'GET_HISTORY_PROFIT';
export const GET_CURRENT_BUY_INFO = 'GET_CURRENT_BUY_INFO';
export const GET_CURRENT_SELL_INFO = 'GET_CURRENT_SELL_INFO';
export const GET_CURRENT_BUY_RESULT = 'GET_CURRENT_BUY_RESULT';
export const GET_CURRENT_SELL_RESULT = 'GET_CURRENT_SELL_RESULT';

/**
 * @module Fund 基金产品相关
 */
export const GET_FUND_PRODUCTS = 'GET_FUND_PRODUCTS';
export const GET_FUND_CURRENCIES = 'GET_FUND_CURRENCIES';
export const GET_FUND_PRODUCT_DETAIL = 'GET_FUND_PRODUCT_DETAIL';
export const GET_FUND_BUY_INFO = 'GET_FUND_BUY_INFO';
export const GET_HOLDING_FUNDS = 'GET_HOLDING_FUNDS';
export const BUY_FUNDS = 'BUY_FUNDS';
export const GET_FUNDS_TRADE_RULES = 'GET_FUNDS_TRADE_RULES';
export const GET_FUNDS_INFORMATION = 'GET_FUNDS_INFORMATION';

/**
 * 用户相关
 */
export const GET_USER_SUMMARY = 'GET_USER_SUMMARY';
export const GET_USER_BALANCE_SUMMARY = 'GET_USER_BALANCE_SUMMARY';
